# Generated by Django 5.0.6 on 2024-06-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='category_id',
        ),
        migrations.AddField(
            model_name='books',
            name='category_id',
            field=models.ManyToManyField(to='books.categories'),
        ),
    ]
