# Generated by Django 5.0.6 on 2024-07-23 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_books_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='books',
            name='category_id',
        ),
        migrations.CreateModel(
            name='BookDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('date_published', models.DateField()),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.authors')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('classification_number', models.IntegerField()),
                ('languange', models.CharField(verbose_name=50)),
                ('call_number', models.CharField(verbose_name=30)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('isbn', models.IntegerField(blank=True, null=True, unique=True)),
                ('edition', models.IntegerField(default=1)),
                ('date_published', models.DateField()),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.authors')),
                ('title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookdisplay')),
            ],
        ),
        migrations.CreateModel(
            name='bookShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
