# Generated by Django 5.0.6 on 2024-07-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_books_author_id_remove_books_category_id_and_more'),
        ('users', '0007_alter_loans_book_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
