# Generated by Django 5.0.6 on 2024-07-23 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_languange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='languange',
        ),
        migrations.AddField(
            model_name='book',
            name='languange_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books.languange'),
            preserve_default=False,
        ),
    ]
