# Generated by Django 5.0.6 on 2024-07-23 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_remove_book_languange_book_languange_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='publisher_id',
        ),
    ]
