# Generated by Django 5.0.6 on 2024-07-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_rename_publisher_book_publisher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='classification_number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
