# Generated by Django 5.0.6 on 2024-07-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_book_classification_number_alter_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_id',
        ),
    ]
