# Generated by Django 5.0.6 on 2024-07-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_remove_book_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdisplay',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='bookdisplay',
            old_name='category_id',
            new_name='category',
        ),
    ]
