# Generated by Django 5.0.6 on 2024-07-24 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_rename_author_id_bookdisplay_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='languange_id',
            new_name='languange',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publisher_id',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title_id',
            new_name='title',
        ),
    ]
