# Generated by Django 5.0.6 on 2024-08-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_rename_languange_id_book_languange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image_url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
