# Generated by Django 5.0.6 on 2024-08-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_book_book_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_image_url',
        ),
        migrations.AddField(
            model_name='bookdisplay',
            name='book_image_url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
