# Generated by Django 5.0.6 on 2024-08-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_genre_bookdisplay_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdisplay',
            name='category',
        ),
        migrations.AddField(
            model_name='bookdisplay',
            name='category',
            field=models.ManyToManyField(to='books.categories'),
        ),
    ]
