# Generated by Django 5.0.6 on 2024-08-26 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date_registered',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.CreateModel(
            name='BookCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_code', models.CharField(max_length=14)),
                ('status', models.CharField(default='available')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
        migrations.DeleteModel(
            name='bookShelf',
        ),
    ]
