# Generated by Django 5.0.6 on 2024-08-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_book_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='stock',
        ),
    ]
