# Generated by Django 5.0.6 on 2024-08-27 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_alter_bookcode_book_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcode',
            old_name='book',
            new_name='detail',
        ),
    ]
