# Generated by Django 5.0.6 on 2024-07-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='return_status',
            field=models.BooleanField(default=False),
        ),
    ]
