# Generated by Django 5.0.6 on 2024-08-24 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_return_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='user_id',
            new_name='user',
        ),
    ]
