# Generated by Django 5.0.6 on 2024-08-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_rename_book_id_loan_book_rename_user_id_loan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
