# Generated by Django 5.0.6 on 2024-08-26 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_book_stock'),
        ('loans', '0005_alter_loan_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookcode'),
        ),
    ]
