# Generated by Django 5.0.6 on 2024-07-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nik',
            field=models.PositiveBigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
