# Generated by Django 5.0.6 on 2024-08-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='Pria', max_length=10),
        ),
    ]
